query product($idInput: String!) {
  product(idInput: $idInput) {
    _id
    name {
      en
      ko
    }
    category
    sub_category
    imageUrl
    #company
    upc_code
    product_code
    rating
    priceInfos {
      #_id
      provider
      month
      price
      link
    }
    nutrients {
      key
      name_en
      name_ko
      value
    }
    additional {
      capability
      oneDaySize
      risk
      certification
      extract
    }
    one_shot_provided
    number_of_servings
    shape
    packing_amount
    effectRating
    costEffectRating
    troubleRating
    convenienceRating
    rePurchaseRating
    updatedAt
    createdAt
  }
}